# Generated by Django 4.0.6 on 2022-08-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=1, verbose_name='用户状态'),
        ),
    ]
